### ISSUE TITLE
Using SheenBidi with utf8

### ISSUE THREAD

**Issue by ericoporto** [Tehreer/SheenBidi#10]
Hi, 

I am looking at a library for Bidi to pair up with Harfbuzz and FreeType for rendering text in a game engine. Do you know any project that is using SheenBidi with those so I can get a little headstart when working with these? Does SheenBidi support emojis? I am using utf8.

**Comment by behdad** [comment]
Check out libraqm as well, which ties FriBidi, HarfBuzz, and FreeType. If FriBidi's license is an issue, I suggest integrating SheenBidi into libraqm. cc @khaledhosny

**Comment by ericoporto** [comment]
@behdad thank you so much for Harfbuzz! I was worried but it took me one day and a half to get going with it - properly rendering Persian.

I looked into Fribid, but I wasn't sure if the license would block console ports, so I decided to look for libraries with other licenses. The game engine I am looking into already has Switch and Xbox ports.

**Comment by behdad** [comment]
Thanks @ericoporto. FriBidi is LGPL'ed, which can cause problem in walled-garden models like iOS indeed. I can't offer any legal advice. Feel free to discuss; I'm tagging @dov who is the current maintainer.

**Comment by mta452** [comment]
@ericoporto The last section in README provides example code for using SheenBidi with UTF-8 encoding.
If you want to look at a game, [supertuxkart](https://github.com/supertuxkart/stk-code) is using it.
If you're considering to use it in iOS or Android, [Tehreer-Cocoa](https://github.com/Tehreer/Tehreer-Cocoa) and [Tehreer-Android](https://github.com/Tehreer/Tehreer-Android) are available.

**Comment by ericoporto** [comment]
@mta452 thank you so much! I will dive into super tux kart to see how they pulled - I think projects using it could be a line in README. 

I plan to use SheenBidi on Android and iOS too, but I like having the same codebase, so I will look into using SheenBidi directly - I am already using SDL or Allegro raster functions so I will see how to wrap it all together. You can close this.

**Comment by mta452** [comment]
Great, I'll close the issue then.
