### ISSUE TITLE
Output mismatch with https://util.unicode.org/UnicodeJsps/bidi.jsp

### ISSUE THREAD

**Issue by honnesh** [Tehreer/SheenBidi#29]
I tried a shortened version of the example text, "یہ ایک )" in https://util.unicode.org/UnicodeJsps/bidi.jsp and it gives a different result compared to SheenBidi for a base direction of LTR. Please take a look

**Comment by mta452** [comment]
Can you share the screenshots of results and explain the differences in both?

**Comment by honnesh** [comment]
Sure, 
<img width="841" alt="Screenshot 2024-11-18 at 10 07 30 AM" src="https://github.com/user-attachments/assets/651e60b5-fd8c-4935-b0e3-9fb0897927b5">

As can be seen in the screenshot above, Unicode's reference implementation has two runs, whereas sheenbidi(using the sample code provided in README) gives me a single level run of the entire text with a  level of 1 when the base direction is set as LTR.

**Comment by mta452** [comment]
Maybe you are passing `SBLevelDefaultLTR` while creating the paragraph object. If you want to explicitly set the direction to LTR, you need to pass `0` as argument value. With this little change, I'm sure you'll see the same result from SheenBidi as well.

Let me know how it goes.

**Comment by mta452** [comment]
It is the base level of the paragraph with `SBLevelDefaultLTR` and `SBLevelDefaultRTL` as special values to apply the rules P2, P3 of the Unicode Bidirectional Algorithm. It is documented over the function's declaration place in `SBAlgorithm.h`.

**Comment by honnesh** [comment]
If rules P2 and P3 are applied if the base level is specified as SBLevelDefaultLTR or SBLevelDefaultRTL, what is the functional difference between using SBLevelDefaultLTR vs. SBLevelDefaultRTL?

**Comment by mta452** [comment]
It would make the difference if no strong character is found in the paragraph. As mentioned in the documentation:
**`SBLevelDefaultLTR`**: _A value specifying to set base level to zero (left-to-right) if there is no strong character._
**`SBLevelDefaultRTL`**: _A value specifying to set base level to one (right-to-left) if there is no strong character._
