### ISSUE TITLE
Confusion regarding mirrored codepoints

### ISSUE THREAD

**Issue by honnesh** [Tehreer/SheenBidi#30]
I am learning about the Bidirectional algorithm and testing out some examples through SheenBidi. I am using Harfbuzz for text shaping after determining the text runs through SheenBidi. A point of confusion is when to mirror codepoints? Do I always need to use the mirrored codepoints in the displayed text or is there a logic to this? Please help.

**Comment by behdad** [comment]
HB takes care of mirroring. You shouldn't do in the bidi algorithm IIRC. @khaledhosny

**Comment by honnesh** [comment]
Thanks, @behdad. On the topic of using Harfbuzz after SheenBidi, should I explicitly set the buffer direction (LTR or RTL) based on SheenBidI or can Harfbuzz reliably determine it if the text is segmented based on level runs?

**Comment by behdad** [comment]
> Thanks, @behdad. On the topic of using Harfbuzz after SheenBidi, should I explicitly set the buffer direction (LTR or RTL) based on SheenBidI or can Harfbuzz reliably determine it if the text is segmented based on level runs?

Exactly.

**Comment by honnesh** [comment]
Exactly as in use SheenBidi's direction instead of letting Harfbuzz guess the direction for each level run?

**Comment by behdad** [comment]
> Exactly as in use SheenBidi's direction instead of letting Harfbuzz guess the direction for each level run?

Yes. Sorry I misread your comment initially.

**Comment by honnesh** [comment]
I am currently letting harfbuzz guess the script and language for each level run. Is this okay?

**Comment by behdad** [comment]
> I am currently letting harfbuzz guess the script and language for each level run. Is this okay?

Not really. For example, if a run has forced direction using format characters, or has no strong characters in it, HB will mis-categorize the direction. Just pass what you get from the bidi algorithm.

**Comment by honnesh** [comment]
I will set the direction on the buffer as determined by bidi algorithm, I am curious to know if I can let harfbuzz guess the language and script of the buffer

**Comment by behdad** [comment]
> I will set the direction on the buffer as determined by bidi algorithm, I am curious to know if I can let harfbuzz guess the language and script of the buffer

Just set the direction, then call the `hb_buffer_guess_segment_properties()`.

**Comment by honnesh** [comment]
Thanks, @behdad. I got all the answers efficiently. Thanks for your work towards Harfbuzz and SheenBidi.

**Comment by khaledhosny** [comment]
Resolving characters with Common script (and Inherited to a lesser extent) can be tricky, especially if they end up in a bidi run with no other character with a set script. My recommendation is to resolve scripts before splitting text into bidi runs. See https://github.com/HOST-Oman/libraqm/blob/8e74fbbfe079c09a3d58c7e0e0942fd8887c62c6/src/raqm.c#L2040 for an example code.

**Comment by honnesh** [comment]
Thanks, Khaled. Would SheenBidi's [ScriptLocator](https://github.com/Tehreer/SheenBidi?tab=readme-ov-file#sbscriptlocator) do the same as _raqm_resolve_scripts?

**Comment by khaledhosny** [comment]
I have not tested it, but after a quick glance it seems to provide comparable functionality.

**Comment by honnesh** [comment]
To summarize, I should determine the bidi runs and then split the runs into segments of the same script and pass those segments to harfbuzz. I should set the direction and script of the segment based on Sheenbidi. Is this correct?

**Comment by honnesh** [comment]
If I split the text based on script and then determine the bidi runs for each of these splits, won't it affect the outcome vs. if I did not split the text?

**Comment by behdad** [comment]
> If I split the text based on script and then determine the bidi runs for each of these splits, won't it affect the outcome vs. if I did not split the text?

You don't split by one first then do the other on top. You do all kinds of segmentations: bidi, script, font, etc. And combine all of them to get segments having all the same properties and shape those.

**Comment by honnesh** [comment]
Hi @behdad , if I split a RTL run into multiple segments because of script changes mid-run, then I would have to reverse the ordering of the new segments to maintain their correct visual positions right?

**Comment by behdad** [comment]
> Hi @behdad , if I split a RTL run into multiple segments because of script changes mid-run, then I would have to reverse the ordering of the new segments to maintain their correct visual positions right?

Correct. I don't know how SheenBidi works, but when the bidi assigns the same RTL level numbers to those runs, the reordering algorithm takes care of those correctly.

I have a linear-time reordering implementation here:

  https://github.com/fribidi/linear-reorder

I think libraqm uses that.

**Comment by mta452** [comment]
@honnesh if you are still looking for help, this is how I resolved it:
* First, create an array of scripts by using `SBScriptLocator`. Here is the relevant [code snippet](https://github.com/unicode-org/text-rendering-tests/blob/b9d34205c4851caf187e153b92d782351ff56245/src/fonttest/tehreerstack_line.cpp#L92-L104).
* Then, resolve bidi-lines by using `SBAlgorithm`, `SBParagraph` and `SBLine`. Here's the relevant [code snippet](https://github.com/unicode-org/text-rendering-tests/blob/b9d34205c4851caf187e153b92d782351ff56245/src/fonttest/tehreerstack_line.cpp#L145-L205). Here, `SheenFigure` is being used for text shaping but the idea is same. Basically you need to iterate over line runs and find out a common run that has the same script and bidi level. You can get the open type tag of the script with `SBScriptGetOpenTypeTag` function and pass this value to harfbuzz. If the level of the bidi-run is odd then it should be treated as right-to-left and if it is even, then it should be treated as left-to-right. You can take a look at this [code block](https://github.com/Tehreer/Tehreer-Android/blob/74aa7286b37efe058971e3bee427214bffbc5ad5/tehreer-android/src/main/jni/ShapingEngine.cpp#L87-L132) for reference.
* If you are working with multiple lines, then you should cache all `SBParapraph` objects, get [runs info](https://github.com/Tehreer/Tehreer-Android/blob/74aa7286b37efe058971e3bee427214bffbc5ad5/tehreer-android/src/main/jni/BidiParagraph.cpp#L84-L98) from there and then shape them individually. After measuring lines with glyph advances, you need to create lines with `SBParagraphCreateLine` function. The line object will provide runs in visual order, which can be rendered afterwards.

Let me know if you need any further clarification.

**Comment by honnesh** [comment]
Thank you, @mta452, for the detailed steps. I have followed a similar approach. Thanks for the follow-up
