### ISSUE TITLE
extern "C" in public headers?

### ISSUE THREAD

**Issue by gidapataki** [Tehreer/SheenBidi#7]
Hi!
Thank you for this library, it is exactly what I looked for as I don't want to include ICU in my project. I'm using it from a C++ code, so I needed `extern "C"`, but it would be nicer, if this would be in the library's public headers at least.

I'm not sure which option would you like better: adding it to every public header or just for the ones declaring functions, so I decided not to open a PR about this, as it's a trivial thing anyway :)

**Comment by mta452** [comment]
Thank you for the comment, but the library is primarily focused on `c89`. The compatibility with other languages, such as `c++`, needs to be addressed in that particular language. Considering this, you can see that I have also explicitly written `extern "C"` in the `test` module.

One way to avoid the repetition would be to use a project level header which wraps all desired `c` headers in an `extern "C"` block.
