### ISSUE TITLE
requirement: Is there a demo for utf-16?

### ISSUE THREAD

**Issue by znsoftm** [Tehreer/SheenBidi#9]
I guess if I input a string of utf-8 characters,  when it will be revert direction, it's hard to handle it when it's represented with utf-8. So is there a demo for utf-16 ? I need to process  uyghur characters.

**Comment by znsoftm** [comment]
I get some character from a book with OCR and need to encode it into the correct form.

**Comment by mta452** [comment]
SheenBidi does not revert the direction, but it provides runs in visual order. The client is free to render the string in reverse order by checking the the level of the run.
SheenBidi can also work on UTF-16 if the client provides such string. Only `SBStringEncodingUTF16` needs to be provided in that case.
